
name: Crawl IQAir Data

on:
  schedule:
    - cron: '0 */1 * * *'  # Run every 4 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  crawl-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}  # Token for push permission
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
          pip install numpy --upgrade
          pip install pandas --upgrade
      - name: Run crawler
        run: python crawl_iqair.py
      
      - name: Merge CSV files
        run: python merge_csv.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Thêm cả file gộp (ví dụ: aqi_all_cities_2025.csv) vào commit
          git add result/* aqi_selected_cities.csv
          git diff --staged --quiet || git commit -m "chore: update AQI data and merged CSV [skip ci]"
          git push origin main
